# Generated by Django 5.2.16 on 2026-07-08 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GranularityBucket',
            fields=[
                ('level', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True)),
                ('role_count', models.PositiveIntegerField(default=0)),
                ('sample_roles', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('slug', models.SlugField(max_length=128, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=255)),
                ('bio_blurb', models.TextField(blank=True)),
                ('lived', models.CharField(blank=True, max_length=64)),
                ('instrument', models.CharField(blank=True, max_length=128)),
                ('traditions', models.JSONField(blank=True, default=list)),
                ('influenced', models.JSONField(blank=True, default=list)),
                ('studied_with', models.JSONField(blank=True, default=list)),
                ('bucket_distribution', models.JSONField(blank=True, default=dict)),
                ('total_notes', models.PositiveIntegerField(default=0)),
                ('principles_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('slug', models.SlugField(max_length=192, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=512)),
                ('note_count', models.PositiveIntegerField(default=0)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='roster.master')),
            ],
            options={
                'ordering': ['master__display_name', 'title'],
            },
        ),
        migrations.CreateModel(
            name='UsageNote',
            fields=[
                ('note_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('run_id', models.CharField(blank=True, max_length=128)),
                ('chord_quality', models.CharField(blank=True, max_length=128)),
                ('function_role', models.CharField(blank=True, max_length=255)),
                ('granularity_level', models.CharField(blank=True, choices=[('a', 'harmonic-family'), ('b', 'voicing-floor'), ('c', 'omission-priority'), ('d', 'color-tone-policy'), ('e', 'substitution-rules'), ('f', 'rhythmic-placement'), ('g', 'voice-leading'), ('h', 'idiom-application'), ('i', 'other')], max_length=1)),
                ('granularity_name', models.CharField(blank=True, max_length=64)),
                ('note_text', models.TextField(blank=True)),
                ('source_principle_ids', models.JSONField(blank=True, default=list)),
                ('provenance', models.JSONField(blank=True, default=dict)),
                ('references', models.JSONField(blank=True, default=list)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_notes', to='roster.book')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_notes', to='roster.master')),
            ],
            options={
                'ordering': ['master__display_name', 'book__title', 'note_id'],
                'indexes': [models.Index(fields=['granularity_level'], name='roster_usag_granula_b7d322_idx'), models.Index(fields=['master', 'granularity_level'], name='roster_usag_master__5b0f63_idx')],
            },
        ),
    ]
