# Generated by Django 5.2.16 on 2026-07-08 22:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roster', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedagogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255)),
                ('credentials', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pedagogue_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='Confirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verdict', models.CharField(choices=[('confirm', 'Confirm classification'), ('correct', 'Correct classification'), ('nuance', 'Add nuance'), ('rereview', 'Flag for re-review')], max_length=16)),
                ('corrected_granularity_level', models.CharField(blank=True, help_text='Only set when verdict=correct and the bucket should change.', max_length=1)),
                ('corrected_function_role', models.CharField(blank=True, help_text='Only set when verdict=correct and the role text should change.', max_length=255)),
                ('comment', models.TextField(blank=True, help_text='Free-form nuance or explanation. Required for nuance/rereview.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usage_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', to='roster.usagenote')),
                ('pedagogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', to='confirmations.pedagogue')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['verdict'], name='confirmatio_verdict_160750_idx'), models.Index(fields=['usage_note', 'verdict'], name='confirmatio_usage_n_8462b0_idx')],
                'constraints': [models.UniqueConstraint(fields=('usage_note', 'pedagogue'), name='one_confirmation_per_pedagogue_per_note')],
            },
        ),
    ]
