# Generated by Django 5.2.16 on 2026-08-18 16:40

import django.db.models.deletion
import ellington_web.confirmations.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confirmations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PedagogueInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=ellington_web.confirmations.models._new_invite_token, editable=False, max_length=128, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('display_name', models.CharField(max_length=255)),
                ('credentials', models.TextField(blank=True, help_text='Optional biographical / credential text carried onto the Pedagogue.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=ellington_web.confirmations.models._default_invite_expiry)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedagogue_invites_sent', to=settings.AUTH_USER_MODEL)),
                ('redeemed_pedagogue', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redeemed_from_invite', to='confirmations.pedagogue')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='confirmatio_email_7d65d9_idx')],
            },
        ),
    ]
